### ISSUE TITLE
IBus example is missing

### ISSUE THREAD

**Issue by stefkin** [monky-hs/monky#24]
I've encountered the following error when using monky 2.0 config example:

```
monky.hs:12:8:
    Could not find module ‘Monky.Examples.IBus’
    Perhaps you meant
      Monky.Examples.Alsa (from monky-2.0.0.0@monky_4iCXLCXT4iT5eAZR63uooi)
      Monky.Examples.CPU (from monky-2.0.0.0@monky_4iCXLCXT4iT5eAZR63uooi)
      Monky.Examples.Disk (from monky-2.0.0.0@monky_4iCXLCXT4iT5eAZR63uooi)
    Use -v to see a list of the files searched for.
Compilation failed
```

IBus object file is missing in .cabal/lib/../../Monky/Examples

**Comment by Ongy** [comment]
The ibus example is not build by default.
Ibus support has a dependency on dbus which itself has quite a few dependencies (most notably xml2 C library, which cabal can not resolve).
To install monky with the ibus example, do  `cabal install -f ibus`.

**Comment by stefkin** [comment]
Ah, I should've realized that by myself. Thank you for the brief response.
