### ISSUE TITLE
Cannot run Monky

### ISSUE THREAD

**Issue by IQubic** [monky-hs/monky#33]
So, I installed this with Cabal, and tried running, but I got the following error the very first time I ran it:

    Monky/Modules.hs:50:0:
         error: missing binary operator before token "("
         #if MIN_VERSION_base(4,8,0)
         ^
    Compilation failed

**Comment by Ongy** [comment]
Can you tell me more about your system?
This is to be expected if one tries to compile monky without cabal, but it should not happen, if the monky library can be found in the package database.

**Comment by IQubic** [comment]
I am running Gentoo Linux with XMonad. I do have cabal. Cloning the repo and running ` cabal install ` worked as expected. Running Monky by typing ` monky ` from terminal yeilds the above output. 

Note I can call monky from any directory at this point. The output is the same.

**Comment by IQubic** [comment]
Yes, compiling with Cabal seems to have solved my issues.

**Comment by IQubic** [comment]
Actually, it doesn't solve anything. I compiled with cabal by running `cabal configure`, and then `cabal build` Running, via `cabal run` this time, still gives the same error message as it did before.

EDIT: turns out `cabal install` did those things already. Not sure why this isn't working.

**Comment by IQubic** [comment]
Alright. I think I have this working. I needed to manually run the executable it the .cabal/bin directory in order to get it working.

However, now I can run it via `monky` from anywhere in my filesystem.

**Comment by Ongy** [comment]
Ah, the executable in `.cabal/bin` should be the only `monky` executable.
It's funny that you found something different. Can you run `which monky` and tell me where the other executable is?


To be able to call it from anywhere, you will have to add the binary to PATH.
You can either copy (or symlink) it into a directory that's in PATH, or add `~/.cabal/bin` to your PATH.

**Comment by IQubic** [comment]
`which monky` returns only `~/.cabal/bin/monky`

**Comment by Ongy** [comment]
Closing this, since there hasn't been anything on it in almost half a year.
