### ISSUE TITLE
Could not find thermal zone

### ISSUE THREAD

**Issue by donat-b** [monky-hs/monky#34]
monky-2.1.0.0

config from an example:
```haskell
import Monky.Examples.CPU

pollPack 5 $ getCPUHandle' ScalingCur
```
Can you help me debug this problem? I don't even know where to start looking right now.
Here's my strace log, if it helps: http://sprunge.us/bBRf

**Comment by belst** [comment]
You can specify a specific thermal zone in `getCPUHandle` (note the missing tick ')

For example:
```hs
import Monky.Examples.CPU

pollPack 5 $ getCPUHandle ScalingCur "thermal_zone0"
```

check `/sys/class/thermal/` for available thermal zones.

**Comment by donat-b** [comment]
Thanks, it works!

I guess auto detection isn't working because my system gives type "pkg-temp-0"?

**Comment by belst** [comment]
`guessThermalZones` checks for the `thermal_zone` prefix. So yes.

**Comment by Ongy** [comment]
It's still a therma_zone, the thing that fails is the auto-detection.
The current auto-detection only works for x86 (for the simple reasons that I have no other devices to test on).

pkg-temp-0? Are you on a soc?

**Comment by donat-b** [comment]
Nope, it's Intel x68_64. Maybe the kernel is giving wrong data?
```3.13.0-85-generic #129-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux```

**Comment by Ongy** [comment]
I checked in the kernel source tree, the type for the thermal zone changed in 3.14, so it's your kernel version that displays it differently.
I will look into the thermal drivers a bit more and decide if I can come up with a better way to detect cpu thermal zone, or keep it as is.
