### ISSUE TITLE
Add preview images to README.md

### ISSUE THREAD

**Issue by gleber** [monky-hs/monky#7]
Currently README does not contain examples of how monky looks like exactly, raising a barrier of entry. Adding some preview images would be nice :)

**Comment by belst** [comment]
got added with a52e16f5cf788432236d45f1b2ef45f78f95cea3

**Comment by Ongy** [comment]
What it looks like is a hard concept for an application that only outputs text, but I added screenshots of my current setups using dzen and the .xbm files linked in the readme.
